table Metric
	lineageTag: ab9010ed-19d6-4eee-ad4b-1f33ab144c19

	column Type
		dataType: string
		lineageTag: 4c4104b9-2121-4f17-a40a-29e8a4af6756
		summarizeBy: none
		sourceColumn: Type
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 12ea8454-d78d-4889-829f-ac4c1a04fb12
		summarizeBy: sum
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition Metric = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk7MSSyqVNJRMlSK1YlWcs0tyMmvTE0tBooYKcXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measure = _t, #"Sort Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measure", type text}, {"Sort Order", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Measure", "Type"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

