table 'All Measures'
	lineageTag: 7dbc5b3d-c04f-4c80-9267-ed3b122a8e42

	measure 'Total Sales' = sum(financials[ Sales])
		lineageTag: 4084a015-dba0-48d7-8b5c-514708f721e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total COGS' = sum(financials[COGS])
		lineageTag: bcc8aa5a-4bc0-4dde-b505-bc728ee5355e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Order' = AVERAGE(financials[Units Sold])
		lineageTag: b926cb76-5745-4829-bb23-56e4f5063d20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Margin' = sum(financials[Profit])
		lineageTag: efb49d9d-bcc7-4790-bd34-941a28638a3a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure Selected' = SELECTEDVALUE(Metrics[Type],"Sales")
		lineageTag: 548cafc4-21c9-4adb-a223-4c1874bef94e

	measure 'Metric Logic' =
			
			SWITCH(
			    TRUE(),
			    'All Measures'[Measure Selected]="Sales",[Total Sales],
			    'All Measures'[Measure Selected]="COGS",[Total COGS],
			    'All Measures'[Measure Selected]="Margin",[Total Margin],
			    [Total Sales]
			    )
		lineageTag: 934c6fcc-7d17-41b6-901c-e11f601e4780

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'All Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

