// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table bikes (BikepointID:string, Street:string, Neighbourhood:string, Latitude:dynamic, Longitude:dynamic, No_Bikes:long, No_Empty_Docks:long) 
.create-merge table bikes1 (Neighbourhood:string) 
.create-merge table bikes4 (BikepointID:string, SUM_No_Bikes:dynamic, Window_End_Time:datetime) 
